build: clean
	go build -o ./out/ascii-banner ./cmd/...
build-prod: clean
	go build -ldflags="-s -w" -o ./out/ascii-banner ./cmd/...
clean:
	@rm -rf ./out
format:
	go fmt ./...
test:
	go test ./...
test-bench:
	go test ./... -bench=.
