on: pull_request
jobs:
  configure:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.5"
      - run: go version
  test:
    runs-on: ubuntu-20.04
    needs: configure
    steps:
      - uses: actions/checkout@v2
      - name: Testing lib
        run: make test
  test_bench:
    runs-on: ubuntu-20.04
    needs: configure
    steps:
      - uses: actions/checkout@v2
      - name: Testing with benchmarks
        run: make test_bench
