on:
  pull_request:
  push:
    branches:
      main
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23"
      - name: Install deps
        run: go mod tidy
        
  test:
    runs-on: ubuntu-latest
    needs: configure
    steps:
      - uses: actions/checkout@v4
      - name: Testing
        run: make test
  lint:
    runs-on: ubuntu-latest
    needs: configure
    steps:
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3