on:
  pull_request:
  push:
    branches:
      main
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23"
      - name: Install deps
        run: go mod tidy
      - name: Test
        run: make test
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3